### ISSUE TITLE
Add support for retrofit

### ISSUE THREAD

**Issue by Axot017** [Iteo/cached#54]

**Comment by jakubtiteo** [comment]
I have prepared small proof of concept and I want to discuss few things about it:
```
@withCache
@RestApi(baseUrl: "https://jsonplaceholder.typicode.com/")
abstract class Retrofiteo {
  factory Retrofiteo(Dio dio) = _CachedRetrofiteo;

  @cached
  @GET("/todos/{id}")
  Future<Todo> getTodo(@Path() int id);
}
```
We are by default only adding underscore to generated class name, retrofit is doing the same so this will result in name collision. To overcome this issue I'm proposing changing generated class name to `_Cached{className}` when retrofit annotation is detected. 

In generated code I'm proposing extending generated retrofit class, this will result in something like this:
```
class _CachedRetrofiteo extends _Retrofiteo {
  _CachedRetrofiteo(Dio dio) : super(dio);

  final _getTodoCached = <String, Todo>{};

  @override
  Future<Todo> getTodo(int id) async {
    final cachedValue = _getTodoCached["${id.hashCode}"];
    if (cachedValue == null) {
      final Todo toReturn;
      try {
        final result = super.getTodo(id);

        toReturn = await result;
      } catch (_) {
        rethrow;
      } finally {}

      _getTodoCached["${id.hashCode}"] = toReturn;
      return toReturn;
    } else {
      return cachedValue;
    }
  }
}
```

Working proof of concept:
```
void main() async {
  final todoApi = Retrofiteo(Dio());
  
  for (int i = 0; i < 3; i++) {
    final sw = Stopwatch();
    sw.start();
    final todo = await todoApi.getTodo(94);
    sw.stop();

    print(jsonEncode(todo.toJson()));
    print("Iteration $i: ${sw.elapsedMilliseconds} ms");
  }
}
```
Output:
```
{"userId":5,"id":94,"title":"facilis modi saepe mollitia","completed":false}
Iteration 0: 295 ms
{"userId":5,"id":94,"title":"facilis modi saepe mollitia","completed":false}
Iteration 1: 0 ms
{"userId":5,"id":94,"title":"facilis modi saepe mollitia","completed":false}
Iteration 2: 0 ms
```

Let me know what do you think about that.

**Comment by Axot017** [comment]
I had similar idea for that. The only thing that i'm not sure about is if refrofit generator will not give any warnings during generation (because class did not use constructor generated by retrofit) which will be quite annoying. Did you check that?

**Comment by jakubtiteo** [comment]
Yes, no warnings from retrofit generator so far

**Comment by jakubtiteo** [comment]
Because retrofit implements the class instead of extending it, it appears there is an issue with `@clearCached` and `@clearAllCached` methods. I found several solutions to this problem:
1. Generating extension on class with `@withCache` annotation

In my opinion, this is the best way of dealing with this issue, wherever it requires discussion about when to generate these extensions. Maybe is it worth adding `@generateClearCached` method, that will work on classes without retrofit?
Maybe this extension should be generated by default on retrofit classes without any additional annotations?
```
extension RetrofiteoCachedExtensions on Retrofiteo {
  _CachedRetrofiteo get _cached => (this as _CachedRetrofiteo);

  void clearSmthCache() {
    // ...
  }

  void clearAllCache() {
    // ...
  }
}

```

2. Using empty `@Get("")` with Future<void>

```
@clearAllCached
@GET("")
Future<void> clearAllCache();
```

In my opinion, this solution is a bit ugly and counterintuitive
