### ISSUE TITLE
Add a way to prevent caching specific results

### ISSUE THREAD

**Issue by julianscheel** [Iteo/cached#81]
It would be useful to have a way inside a cached function to signal that a certain result must not be cached.
In particular we are caching results from a server, which can in some situations return data that is explicitly not allowed to be cached. But this can only be known after the data was loaded, not before issuing the call. Thus `ignoreCache` can not be used to solve the issue here.

Any thoughts on a nice way to support this? In our case we could for example pass a list of types that must not be cached.

**Comment by Axot017** [comment]
Sounds like a very useful feature which we are still missing. Thanks for reporting that!
My proposition how we can achieve this it to add optional argument `where:` to `@Cached(...)` annotation which will have type `FutureOr<bool> Function(dynamic)` (`dynamic` because in annotation context we don't know return type of cached function). This function will be triggered before caching value, if it returns `true` value will be cached if `false` it will be ignored. So it will look like this: 

```dart
import 'package:http/http.dart' as http;

@WithCache()
abstract class RemoteRepository implements _$RemoteRepository {
  factory RemoteRepository() = _RemoteRepository;

  @Cached(where: _test)
  Future<Response> getSthData() {
    return http.post(...);
  }
}

Future<bool> _test(dynamic response) async {
  // `response` will have always the same type as return type of method where `_test` function was used
  // so in this case it will be `getSthData` method return type `Future<Response>`
  final response = await (response as Future<http.Response>); 

  return response.code == 200;
}
```

Will suit your needs @julianscheel?

**Comment by julianscheel** [comment]
Yes, that would work perfectly fine!

**Comment by Axot017** [comment]
Version 1.5.0 containing this feature is now available on pub.dev. 
During development we decided to simplify it a little bit. `where` argument in annotation does not require specific Function definition. This means that test function instead of this:

```dart
Future<bool> _test(dynamic response) async {
  final response = await (response as Future<http.Response>); 

  return response.code == 200;
}
```

can look like this:

```dart
Future<bool> _test(Future<http.Response> response) async {
  return response.code == 200;
}
```

Types will be checked during code generation.
